### PR TITLE
Feature/site-map

### PR DESCRIPTION
**Pull request by HackMort**
Added a simple site-map page.

Update cookie placement on mobile and desktop based on Figma v4. 

Updated cookie code to handle the new position of the cookie banner on desktop view & more.

### CODE REVIEW

**Review by elian-dev — CHANGES_REQUESTED** [review]
According to figma is over the main menu
**Figma:**
image
**Site:**
image

**Comment by Daniel-Gomez-jpg** [comment]
href in ALP ACADEMY link has to be updated to href="/alpd-academy/" for the SITE MAP

**Comment by HackMort** [comment]
> href in ALP ACADEMY link has to be updated to href="/alpd-academy/" for the SITE MAP

This will be fixed in a separate branch

**Comment by HackMort** [comment]
> According to figma is over the main menu **Figma:** image **Site:** image

Thank you! It's fixed.

**Comment by HackMort** [comment]
> href in ALP ACADEMY link has to be updated to href="/alpd-academy/" for the SITE MAP

Thanks, It's fixed.

**Pull request merged**
